\c bud_dev;

INSERT INTO products (name, description, price, image) VALUES
('Wedding Cake','Wedding Cake, also known as "Triangle Mints #23," is a potent type of indica-hybrid marijuana strain made by crossing Triangle Kush with Animal Mints. Fun fact: In Canada, this strain is known as Pink Cookies. The Wedding Cake strain provides relaxing and euphoric effects that calm the body and mind. This strain yields a rich and tangy flavor profile with undertones of earthy pepper. Medical marijuana patients choose Wedding Cake to help relieve symptoms associated with pain, insomnia and appetite loss. Consumers with a low THC tolerance should enjoy this strain with an extra slice of care due to its high THC content. Wedding Cake has soared in popularity over the years and was named Leafly Strain of the Year in 2019.', 42, 'https://leaf.expert/wp-content/uploads/2018/04/image3-1.jpeg'  ),
('Gelato', 'Gelato, also known as "Larry Bird" and "Gelato #42" is an evenly-balanced hybrid marijuana strain made from a crossing of Sunset Sherbet and Thin Mint Girl Scout Cookies. With its balance of indica & sativa, this strain produces a euphoric high accompanied by strong feelings of relaxation. Consumers who have smoked Gelato say the effects of the strain come on quickly.', 52, 'https://www.potvalet.com/wp-content/uploads/2018/05/Gelato-Cannabis-Strain.jpg'),
('Dosidos', 'Dosidos, is an indica-dominant hybrid marijuana.', 52, 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.JsD7Cg9HgNTqSC2HQtTIVQHaEo%26pid%3DApi&f=1'),
('Ice','Ice is a hybrid marijuana strain made by combining multiple strains into one seed line: Skunk #1, Afghani, Northern Lights, and Shiva. This strain produces sedating effects accompanied with a body buzz. Ice has an aroma that smells like diesel. Growers say this strain produces high yields with incredible trichome production. Ice is the ideal strain for a lazy afternoon at home when you have nothing to do.', 42, 'https://www.mailorder-marijuana.com/wp-content/uploads/2020/07/ice-cream-weed-strain.jpg' );


